version: "3.8"

services:
  torrenttotraktv:
    build: .
    container_name: torrenttotraktv
    restart: "no"

    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      QBITIP: ${QBITIP}
      QBITUSER: ${QBITUSER}
      QBITPASS: ${QBITPASS}
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID}
      #TRAKT_TOKEN: ${TRAKT_TOKEN}
      TRAKT_CLIENT_SECRET: ${TRAKT_CLIENT_SECRET}
      TRAKT_USERNAME: ${TRAKT_USERNAME}
      TRAKT_LIST_SLUG: ${TRAKT_LIST_SLUG}
      HA_WEBHOOKERROR_URL: ${HA_WEBHOOKERROR_URL}
    dns:
      - 1.1.1.1
      - 1.0.0.1



    volumes:
      - app_logs:/app/logs

volumes:
  app_logs: